CREATE DATABASE ESTOKWEB DEFAULT CHARACTER SET utf8;

USE ESTOKWEB;

/* Estrutura da tabela categoria */

CREATE TABLE CATEGORIA (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(45) NOT NULL,
	PRIMARY KEY(ID)
);

/* Estrutura da tabela produto */

CREATE TABLE PRODUTO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(250) NOT NULL,
	ESTOQUE_MINIMO INT(3) NOT NULL,
	ESTOQUE_ATUAL INT(3) NOT NULL,
	PRECO_CUSTO FLOAT NOT NULL,
	PRECO_VENDA FLOAT NOT NULL,
	CATEGORIA_ID INT(11) NOT NULL,
	PRIMARY KEY (ID),
	KEY FK_PRODUTO_CATEGORIA1_IDX (CATEGORIA_ID),
	CONSTRAINT FK_PRODUTO_CATEGORIA1_IDX FOREIGN KEY (CATEGORIA_ID) REFERENCES CATEGORIA (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

/* Estrutura da tabela usuario */

CREATE TABLE USUARIO (
	ID INT(11) NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(150) NOT NULL,
	CPF VARCHAR(14) NOT NULL UNIQUE,
	LOGIN VARCHAR(30) NOT NULL UNIQUE,
	SENHA VARCHAR(12) NOT NULL,
	TIPO CHAR(2) NOT NULL DEFAULT 'c',
	PRIMARY KEY (ID)
);

/* Estrutura da tabela pedvend (Pedido de Venda) */

create table PEDVEND (
	CODPEDVEND int not null auto_increment,
	CODPRODUTO int not null,
	QTD int not null,
	VALOR_PROD float not null,
	VALOR_TOTAL float not null,
	DT_VENDA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	constraint PK_PEDVEND primary key(CODPEDVEND),
	constraint FK_CODPRODUTO FOREIGN KEY (CODPRODUTO)
	REFERENCES PRODUTO (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);